services:
  mongo:
    image: mongo:7
    container_name: mercadozetta-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mercadozetta-mongo-data:/data/db

volumes:
  mercadozetta-mongo-data:
