export const appRoutes = {
  home: '/',
  login: '/login',
  register: '/register',
  newProduct: '/products/new',
  editProduct: (productId: string) => `/products/${productId}/edit`,
  cart: '/cart',
  checkout: '/checkout',
  buyerOrders: '/orders',
  addresses: '/account/addresses',
  passwordReset: '/password-reset',
  passwordResetConfirmation: '/password-reset/confirm',
  emailVerification: '/email-verification',
  emailVerificationConfirmation: '/email-verification/confirm',
  notifications: '/notifications',
  sellerOrders: '/seller/orders',
  account: '/account',
  emailChangeConfirmation: '/account/email-change/confirm',
  productDetail: (productId: string) => `/products/${productId}`,
  sellerProducts: (sellerId: string) => `/sellers/${sellerId}`,
  sellerProfile: (sellerId: string) => `/sellers/${sellerId}/profile`,
};

export const routePatterns = {
  home: '/',
  login: '/login',
  register: '/register',
  newProduct: '/products/new',
  editProduct: '/products/:productId/edit',
  cart: '/cart',
  checkout: '/checkout',
  buyerOrders: '/orders',
  addresses: '/account/addresses',
  passwordReset: '/password-reset',
  passwordResetConfirmation: '/password-reset/confirm',
  emailVerification: '/email-verification',
  emailVerificationConfirmation: '/email-verification/confirm',
  notifications: '/notifications',
  sellerOrders: '/seller/orders',
  account: '/account',
  emailChangeConfirmation: '/account/email-change/confirm',
  productDetail: '/products/:productId',
  sellerProducts: '/sellers/:sellerId',
  sellerProfile: '/sellers/:sellerId/profile',
};

export const apiRoutes = {
  login: '/auth/login',
  session: '/auth/session',
  refresh: '/auth/refresh',
  logout: '/auth/logout',
  logoutCurrent: '/auth/logout/current',
  sessions: '/auth/sessions',
  revokeSession: (sessionId: string) => `/auth/sessions/${sessionId}`,
  users: '/users',
  products: '/products',
  productDetail: (productId: string) => `/products/${productId}`,
  productInventory: (productId: string) => `/products/${productId}/inventory`,
  productStatus: (productId: string) => `/products/${productId}/status`,
  sellerProfile: (sellerId: string) => `/users/${sellerId}`,
  sellerProducts: (sellerId: string) => `/users/${sellerId}/products`,
  cart: '/cart',
  cartItems: '/cart/items',
  cartItem: (productId: string) => `/cart/items/${productId}`,
  watchlist: '/watchlist',
  watchlistItem: (productId: string) => `/watchlist/${productId}`,
  orders: '/orders',
  orderStatus: (orderId: string) => `/orders/${orderId}/status`,
  checkoutQuote: '/checkout/quote',
  deliveryAddresses: '/account/addresses',
  deliveryAddress: (addressId: string) => `/account/addresses/${addressId}`,
  emailVerificationRequests: '/auth/email-verification/requests',
  emailVerificationConfirmations: '/auth/email-verification/confirmations',
  passwordResetRequests: '/auth/password-reset/requests',
  passwordResetConfirmations: '/auth/password-reset/confirmations',
  sellerOperations: '/seller/operations',
  reviews: (productId: string) => `/products/${productId}/reviews`,
  notifications: '/notifications',
  notification: (notificationId: string) => `/notifications/${notificationId}`,
  unreadNotificationCount: '/notifications/unread-count',
  accountProfile: '/account/profile',
  passwordChanges: '/account/password-changes',
  emailChanges: '/account/email-changes',
  emailChangeConfirmations: '/auth/email-change/confirmations',
  accountDeactivation: '/account/deactivation',
};
