import logo from '../assets/mercadozetta-logo.png';
import type { BrandConfig } from './schema';

export const defaultBrand: BrandConfig = {
    tenantId: 'mercadozetta',
    brandName: 'MercadoZetta',
    marketplaceName: 'MercadoZetta',
    logo,
    favicon: logo,
    primaryColor: '#fff159',
    secondaryColor: '#3483fa',
    accentColor: '#00a650',
    surfaceColor: '#ffffff',
    textColor: '#333333',
    currency: 'BRL',
    locale: 'pt-BR',
    supportEmail: 'support@mercadozetta.example',
    legalName: 'MercadoZetta',
    copy: {
        header: {
            loginAction: 'Entrar',
            logoutAction: 'Sair',
            loggedUserFallback: 'Usuário logado',
        },
        catalog: {
            searchAction: 'Buscar produtos',
            searchPlaceholder: 'Buscar produto',
            categoryFilterLabel: 'Categoria',
            categoryFilterPlaceholder: 'Todas as categorias',
            availabilityFilterLabel: 'Disponibilidade',
            availabilityAnyLabel: 'Qualquer disponibilidade',
            availabilityInStockLabel: 'Em estoque',
            availabilitySoldOutLabel: 'Somente esgotados',
            sortLabel: 'Ordenar produtos',
            sortNewestLabel: 'Mais recentes',
            sortOldestLabel: 'Mais antigos',
            sortNameLabel: 'Nome',
            sortInventoryLabel: 'Maior estoque',
            loading: 'Carregando produtos...',
            loadError: 'Não foi possível carregar os produtos.',
            empty: 'Nenhum produto encontrado',
            descriptionLabel: 'Descrição:',
            priceUnavailableLabel: 'Preço sob consulta',
            inventoryLabel: 'Disponível:',
            soldOutLabel: 'Esgotado',
            categoryLabel: 'Categoria:',
            subcategoryLabel: 'Subcategoria:',
            sellerLabel: 'Vendedor:',
            statusLabel: 'Status:',
            detailsAction: 'Ver detalhes',
            watchAction: 'Favoritar',
            watchingAction: 'Favorito',
            cartAction: 'Carrinho',
            inCartAction: 'No carrinho',
            statusLabels: {
                draft: 'Rascunho',
                active: 'Ativo',
                paused: 'Pausado',
                sold_out: 'Esgotado',
                archived: 'Arquivado',
            },
        },
        home: {
            headline: 'Encontre ofertas do marketplace',
            subtitle: 'Pesquise produtos, veja disponibilidade e acompanhe vendedores em uma experiência pronta para demonstrações white-label.',
            sellerActionLabel: 'Área do vendedor',
            createAccountAction: 'Criar conta',
            createProductAction: 'Anunciar produto',
        },
        forms: {
            createAccountAction: 'Criar conta',
            loginAction: 'Entrar',
            createProductAction: 'Criar anúncio',
            productStatusLabel: 'Status do produto',
            categoryLabel: 'Categoria',
            subcategoryLabel: 'Subcategoria',
            uploadImageLabel: 'Enviar imagem',
        },
        validation: {
            loginRequiredForProduct: 'Entre para criar um anúncio.',
            accountCreateError: 'Não foi possível criar a conta. Tente novamente.',
            productCreateError: 'Não foi possível criar o anúncio. Tente novamente.',
            invalidCredentials: 'E-mail ou senha inválidos',
        },
    },
    features: {
        sellerPages: true,
        productCreation: true,
        publicCatalog: true,
        checkout: false,
        reviews: false,
        favorites: false,
        inventory: true,
    },
};
